[env:beacon-tof]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli

monitor_speed = 921600

; Toutes les librairies sont dans lib/ (versions modifiées du projet original)
; Pas de lib_deps externes
